### ISSUE TITLE
If p equal q,how to get the answer?

### ISSUE THREAD

**Issue by wcc526** [RsaCtfTool/RsaCtfTool#286]
n = 2748273503889903073409771835178850606219449864742229578820234868709625064941462137378030484842204237859742493426092565797288611485452542475230408037342474501870686715875205194915851845128324954599045156951309384494407143874987183935100572113196535165766935227900231834867393599912466934605007948826760964334458177046412218716528227093295472754352489950048879564382945435406477096326077733704963825552882052587418455612417384968736124326399830065687516280100218014658645688467710043266590115573345615967546681454973512474894522506738190047702601558110861623430262015979684083735036427355522401248026501519281555957601

http://www.factordb.com/index.php?query=2748273503889903073409771835178850606219449864742229578820234868709625064941462137378030484842204237859742493426092565797288611485452542475230408037342474501870686715875205194915851845128324954599045156951309384494407143874987183935100572113196535165766935227900231834867393599912466934605007948826760964334458177046412218716528227093295472754352489950048879564382945435406477096326077733704963825552882052587418455612417384968736124326399830065687516280100218014658645688467710043266590115573345615967546681454973512474894522506738190047702601558110861623430262015979684083735036427355522401248026501519281555957601

e = 58134567416061346246424950552806959952164141873988197038339318172373514096258823300468791726051378264715940131129676561677588167620420173326653609778206847514019727947838555201787320799426605222230914672691109516799571428125187628867529996213312357571123877040878478311539048041218856094075106182505973331343540958942283689866478426396304208219428741602335233702611371265705949787097256178588070830596507292566654989658768800621743910199053418976671932555647943277486556407963532026611905155927444039372549162858720397597240249353233285982136361681173207583516599418613398071006829129512801831381836656333723750840780538831405624097443916290334296178873601780814920445215584052641885068719189673672829046322594471259980936592601952663772403134088200800288081609498310963150240614179242069838645027877593821748402909503021034768609296854733774416318828225610461884703369969948788082261611019699410587591866516317251057371710851269512597271573573054094547368524415495010346641070440768673619729280827372954003276250541274122907588219152496998450489865181536173702554116251973661212376735405818115479880334020160352217975358655472929210184877839964775337545502851880977049299029101466287659419446724781305689536816523774995178046989696610897508786776845460908137698543091418571263630383061605011820139755322231913029643701770497299157169690586232187419462594477116374977216427311975598620616618808494138669546120288334682865354702356192972496556372279363023366842805886601834278434406709218165445335977049796015123909789363819484954615665668979

**Comment by daedalus** [comment]
If p equal q then you have a perfect square and a trivial factorization case, not much to do.

**Comment by wcc526** [comment]
the ctf problem is 

enc.txt
```
NTE1NDY0NDc1NTZDNkM0RjRFNDUzNTU3NTI1NDREN0E0RDMxNEU1QTU2MzA2NzMwNEQzMTRFNTY1MzQ1NTI0NjUxNkI3ODUxNEQzMTU2NTQ1NzU1NUE0RDRFNkIzOTU3NTI1NTY0NEU1MzZDNEE1NTU0NDQ0QTQ4NTQ1NDUyNTc1NjU0NUE1ODU2NTY2NDU2NTYzMDc0NUE1MTZDNkM0OTU2NkI2QjMwNTI1NDRFNTE1MTZDNDU3OTRFNTQ0RTU3NTU0NTU2NDY1NDQ1NEE0QzUyNDU3MDQ4NTIzMDM4Nzk1MTU1NzQ0QTU2NDQ1QTU1NTM2QTY0NTk1NTU1MzE1MTUyNkE1NjUxNTM0NjU1MzA1MzU2NkYzMjU3NkM0RTRBNTc1NDU5MzI1MzQ2NTY0QzUxMzE2ODRCNEQ2QTUyNTA1MjU2NUE1NTUyN0E1MjU0NTM1NTcwNEI1NzQ2NkYzMzU0NkIzNDMzNTEzMDZDNEE1NDU1NEU1QTU1MzAzMTQ3NTEzMTZDNDI1NjZDNzA0ODU0NTQ1QTU2NTU2QzU5MzI0RTZDNTI0MjU3NDQ1MTMzNTQ2QzRBNTk0RTU1NDY1ODUyNkIzOTQzNTQ2QzY4NEM1NzZCNzg1ODU3NDY2QzU5NTY0NTVBNjE1NzZDNTkzMTRENkM1QTU3NTM1NTU2NUE0RTU2NDUzMTUxNTU0NjYxNTU1NTcwNDI1MjQ0NTUzMjU1MzA2NDUxNTI0NTVBNTI1NDMxNjg1MTUzNkE1OTMxNTQ1NTY0NDI1MTZCNUE1NTUyN0E0OTMzNTQ0NTczMzE1NTdBNjQ0QjUzNTY0QTU3NTc0NDRBNjE1MjMxNEU0NDRFNkM0RTRENTI0NjY4NDg1NjQ2NTY1NDU0MzA0NjQyNTQ0NTUyNUE0RTQ1MzE1OTUxNTY0MjU0NTM0NDRBNEE1NTU0NDkzMDUxNkI0QTQ3NTQ2QzQ2NDM1NjU1NTI1NDU3NDY1QTU2NEU2QjQ2NUE0RTQ0NDkzMTUyNDU1MjQ5NEQ2QTRBNEM0RTQ1NDY0RjU1MzA1MTMwNTE1NjU2NEM0RDdBNTE3OTU3NkM0OTMzNTM1NjUyNDc1NTU2NTI0RTU2MzE2Rjc5NTc2QTY0NTE1NDZBNTI0NjU3NTY1QTU1NEU2QTU1N0E1NjZDNDEzMDRFNTU0NjUxNTU1NTZDNTI1MTMwNzQ1NjUyNkM1QTQ0NEQ2QTVBNTk1NDZCNzMzMjU1NkM1MjU1NTc1NTU2NDI1NzZCNTI0NDREMzA2QjMwNTU2QzZDNTI0RTQ2NDY0NzU0NTU0RTQ0NTE2QjUyNEE1NzZCNjQ0NzU3NkM2NDRDNTc0NTU2NEU0RDMwMzU0NDU2MzE2ODRBNTc1NTQ5MzM1NDU1NUE1NzUyNTUzMTRENTUzMDcwNDc0RTU1NEE1QTUyNkM2RjdBNTQzMTRFNEQ1NTQ2NDUzOTUwNTQzMDM5NTA1NDMwM0Q
```

pub.txt
```
n = 2748273503889903073409771835178850606219449864742229578820234868709625064941462137378030484842204237859742493426092565797288611485452542475230408037342474501870686715875205194915851845128324954599045156951309384494407143874987183935100572113196535165766935227900231834867393599912466934605007948826760964334458177046412218716528227093295472754352489950048879564382945435406477096326077733704963825552882052587418455612417384968736124326399830065687516280100218014658645688467710043266590115573345615967546681454973512474894522506738190047702601558110861623430262015979684083735036427355522401248026501519281555957601

e = 58134567416061346246424950552806959952164141873988197038339318172373514096258823300468791726051378264715940131129676561677588167620420173326653609778206847514019727947838555201787320799426605222230914672691109516799571428125187628867529996213312357571123877040878478311539048041218856094075106182505973331343540958942283689866478426396304208219428741602335233702611371265705949787097256178588070830596507292566654989658768800621743910199053418976671932555647943277486556407963532026611905155927444039372549162858720397597240249353233285982136361681173207583516599418613398071006829129512801831381836656333723750840780538831405624097443916290334296178873601780814920445215584052641885068719189673672829046322594471259980936592601952663772403134088200800288081609498310963150240614179242069838645027877593821748402909503021034768609296854733774416318828225610461884703369969948788082261611019699410587591866516317251057371710851269512597271573573054094547368524415495010346641070440768673619729280827372954003276250541274122907588219152496998450489865181536173702554116251973661212376735405818115479880334020160352217975358655472929210184877839964775337545502851880977049299029101466287659419446724781305689536816523774995178046989696610897508786776845460908137698543091418571263630383061605011820139755322231913029643701770497299157169690586232187419462594477116374977216427311975598620616618808494138669546120288334682865354702356192972496556372279363023366842805886601834278434406709218165445335977049796015123909789363819484954615665668979
```

Could you help me answer this question, Thank you!

**Comment by Nixiabing** [comment]
> the ctf problem is
> 
> enc.txt
> 
> ```
> NTE1NDY0NDc1NTZDNkM0RjRFNDUzNTU3NTI1NDREN0E0RDMxNEU1QTU2MzA2NzMwNEQzMTRFNTY1MzQ1NTI0NjUxNkI3ODUxNEQzMTU2NTQ1NzU1NUE0RDRFNkIzOTU3NTI1NTY0NEU1MzZDNEE1NTU0NDQ0QTQ4NTQ1NDUyNTc1NjU0NUE1ODU2NTY2NDU2NTYzMDc0NUE1MTZDNkM0OTU2NkI2QjMwNTI1NDRFNTE1MTZDNDU3OTRFNTQ0RTU3NTU0NTU2NDY1NDQ1NEE0QzUyNDU3MDQ4NTIzMDM4Nzk1MTU1NzQ0QTU2NDQ1QTU1NTM2QTY0NTk1NTU1MzE1MTUyNkE1NjUxNTM0NjU1MzA1MzU2NkYzMjU3NkM0RTRBNTc1NDU5MzI1MzQ2NTY0QzUxMzE2ODRCNEQ2QTUyNTA1MjU2NUE1NTUyN0E1MjU0NTM1NTcwNEI1NzQ2NkYzMzU0NkIzNDMzNTEzMDZDNEE1NDU1NEU1QTU1MzAzMTQ3NTEzMTZDNDI1NjZDNzA0ODU0NTQ1QTU2NTU2QzU5MzI0RTZDNTI0MjU3NDQ1MTMzNTQ2QzRBNTk0RTU1NDY1ODUyNkIzOTQzNTQ2QzY4NEM1NzZCNzg1ODU3NDY2QzU5NTY0NTVBNjE1NzZDNTkzMTRENkM1QTU3NTM1NTU2NUE0RTU2NDUzMTUxNTU0NjYxNTU1NTcwNDI1MjQ0NTUzMjU1MzA2NDUxNTI0NTVBNTI1NDMxNjg1MTUzNkE1OTMxNTQ1NTY0NDI1MTZCNUE1NTUyN0E0OTMzNTQ0NTczMzE1NTdBNjQ0QjUzNTY0QTU3NTc0NDRBNjE1MjMxNEU0NDRFNkM0RTRENTI0NjY4NDg1NjQ2NTY1NDU0MzA0NjQyNTQ0NTUyNUE0RTQ1MzE1OTUxNTY0MjU0NTM0NDRBNEE1NTU0NDkzMDUxNkI0QTQ3NTQ2QzQ2NDM1NjU1NTI1NDU3NDY1QTU2NEU2QjQ2NUE0RTQ0NDkzMTUyNDU1MjQ5NEQ2QTRBNEM0RTQ1NDY0RjU1MzA1MTMwNTE1NjU2NEM0RDdBNTE3OTU3NkM0OTMzNTM1NjUyNDc1NTU2NTI0RTU2MzE2Rjc5NTc2QTY0NTE1NDZBNTI0NjU3NTY1QTU1NEU2QTU1N0E1NjZDNDEzMDRFNTU0NjUxNTU1NTZDNTI1MTMwNzQ1NjUyNkM1QTQ0NEQ2QTVBNTk1NDZCNzMzMjU1NkM1MjU1NTc1NTU2NDI1NzZCNTI0NDREMzA2QjMwNTU2QzZDNTI0RTQ2NDY0NzU0NTU0RTQ0NTE2QjUyNEE1NzZCNjQ0NzU3NkM2NDRDNTc0NTU2NEU0RDMwMzU0NDU2MzE2ODRBNTc1NTQ5MzM1NDU1NUE1NzUyNTUzMTRENTUzMDcwNDc0RTU1NEE1QTUyNkM2RjdBNTQzMTRFNEQ1NTQ2NDUzOTUwNTQzMDM5NTA1NDMwM0Q
> ```
> 
> pub.txt
> 
> ```
> n = 2748273503889903073409771835178850606219449864742229578820234868709625064941462137378030484842204237859742493426092565797288611485452542475230408037342474501870686715875205194915851845128324954599045156951309384494407143874987183935100572113196535165766935227900231834867393599912466934605007948826760964334458177046412218716528227093295472754352489950048879564382945435406477096326077733704963825552882052587418455612417384968736124326399830065687516280100218014658645688467710043266590115573345615967546681454973512474894522506738190047702601558110861623430262015979684083735036427355522401248026501519281555957601
> 
> e = 58134567416061346246424950552806959952164141873988197038339318172373514096258823300468791726051378264715940131129676561677588167620420173326653609778206847514019727947838555201787320799426605222230914672691109516799571428125187628867529996213312357571123877040878478311539048041218856094075106182505973331343540958942283689866478426396304208219428741602335233702611371265705949787097256178588070830596507292566654989658768800621743910199053418976671932555647943277486556407963532026611905155927444039372549162858720397597240249353233285982136361681173207583516599418613398071006829129512801831381836656333723750840780538831405624097443916290334296178873601780814920445215584052641885068719189673672829046322594471259980936592601952663772403134088200800288081609498310963150240614179242069838645027877593821748402909503021034768609296854733774416318828225610461884703369969948788082261611019699410587591866516317251057371710851269512597271573573054094547368524415495010346641070440768673619729280827372954003276250541274122907588219152496998450489865181536173702554116251973661212376735405818115479880334020160352217975358655472929210184877839964775337545502851880977049299029101466287659419446724781305689536816523774995178046989696610897508786776845460908137698543091418571263630383061605011820139755322231913029643701770497299157169690586232187419462594477116374977216427311975598620616618808494138669546120288334682865354702356192972496556372279363023366842805886601834278434406709218165445335977049796015123909789363819484954615665668979
> ```
> 
> Could you help me answer this question, Thank you!

#!/usr/bin/python
#coding:utf-8

import base64
import gmpy2
import libnum
from Crypto.Util.number import long_to_bytes,bytes_to_long

n = 2748273503889903073409771835178850606219449864742229578820234868709625064941462137378030484842204237859742493426092565797288611485452542475230408037342474501870686715875205194915851845128324954599045156951309384494407143874987183935100572113196535165766935227900231834867393599912466934605007948826760964334458177046412218716528227093295472754352489950048879564382945435406477096326077733704963825552882052587418455612417384968736124326399830065687516280100218014658645688467710043266590115573345615967546681454973512474894522506738190047702601558110861623430262015979684083735036427355522401248026501519281555957601
e = 58134567416061346246424950552806959952164141873988197038339318172373514096258823300468791726051378264715940131129676561677588167620420173326653609778206847514019727947838555201787320799426605222230914672691109516799571428125187628867529996213312357571123877040878478311539048041218856094075106182505973331343540958942283689866478426396304208219428741602335233702611371265705949787097256178588070830596507292566654989658768800621743910199053418976671932555647943277486556407963532026611905155927444039372549162858720397597240249353233285982136361681173207583516599418613398071006829129512801831381836656333723750840780538831405624097443916290334296178873601780814920445215584052641885068719189673672829046322594471259980936592601952663772403134088200800288081609498310963150240614179242069838645027877593821748402909503021034768609296854733774416318828225610461884703369969948788082261611019699410587591866516317251057371710851269512597271573573054094547368524415495010346641070440768673619729280827372954003276250541274122907588219152496998450489865181536173702554116251973661212376735405818115479880334020160352217975358655472929210184877839964775337545502851880977049299029101466287659419446724781305689536816523774995178046989696610897508786776845460908137698543091418571263630383061605011820139755322231913029643701770497299157169690586232187419462594477116374977216427311975598620616618808494138669546120288334682865354702356192972496556372279363023366842805886601834278434406709218165445335977049796015123909789363819484954615665668979
p = 7240440478968188528791354594269918982644303179617644370115506971406690195487664027398624125892383640927549736729366652588945259160460451669283632550038393

phi = p**4-p**3

c = 983825518481276839776007071648153231214121816478669335658940370969537417449682300121308667390007689242125384660722140861555893023272345342359725363618136413744259796613111031345350663605231386074560542966684100675544320011440019910022509554679621615173908118847300166341298161327552506271656970720621088118850392993789577112679137400398285000315738359561470258659021484725025831251222677436247169786187036709130777880355242747001997455053444097272842958745008870371117236935845401457445293436995583399064758810223663547887463275271034139608727238955895560187219609003163789751399672984999928884396522804262586698620
d = gmpy2.invert(e,phi)
m = pow(c,d,n)
print long_to_bytes(m)

**Comment by daedalus** [comment]
This does not seem to be a bug related to this tool.

**Comment by wcc526** [comment]
Thank you! it's just a ctf problem,but the answer is not seem like flag?

```
b'\x06h\xc0\xe3\x0f\xdcl\xf8u9i\x83\x03\xcd\xd6\xbewj\x12\xd3\xc6\xdfL\xa4\x9fg\xbcm\x82\xe9\xc2\x7f\xa3\xdc\x07\x00 F7\xd3\xe9V\xdc\xfc\xca:\xe6\x9b\x8a\x96\x1ct\xc7u[Zm\xb57\xe7\xf5*\xd6M\xa8\xa4\\\xaaq\x1a\xc6(\x80r\x9d\xecB\x06R\xfbn\xff\x9af<U\xe9\x89\x07\xc1K\xfd\x81\x8d\xb1\x07\xdch\x14\x07&\xe9{\xb2\xdd\x89\xbc\xf1\xabL;\xdb^\x87\x1aV\x96;\x95P/\x826y\xb9\xa40\xe7f\x04\xb8\xa7S\xb8\xb5\xe8d-\x95\x8d\xe6\x1cA\x93\xef\xbcrx*+\x0c\xd5\x12\xf8e\xf4\xbd$\x7f0\n\xfc\xe4\xcclm\xf6\\\xf7ua\x838c!\xf0\x10~1\xad\xdf9%\x85\n\xf5\xd1\x7f\xe0E[\xae\x8b\xdeW\x9c\xac\x89/^\xdeN\x11\x9f\xd4\xc4g\x91\xabL\xc7h,\xc9c\x1d\x8c\xf3Rc\x1dD\x8d\x01\xb6\n\xec\x12\xf7\xfc\xc9\x100?\xc2n\x1c-\xa6\xcb\xbc\xae39\x03\x9b\xbad \x7f^\xd4r\xbb4z'
```

**Comment by HEIDIHANSON** [comment]
@Nixiabing

**Comment by daedalus** [comment]
@Ganapati ack to close this?

**Comment by daedalus** [comment]
Fixed in the PR https://github.com/RsaCtfTool/RsaCtfTool/pull/321
Since p=q == p^2

**Comment by HEIDIHANSON** [comment]
just got into my email after three months please clarify

**Comment by daedalus** [comment]
If p=q then n = p^2 or n = q^2 then p = isqrt(n) or q = isqrt(n).
