### ISSUE TITLE
hastads attack not working

### ISSUE THREAD

**Issue by mike01** [RsaCtfTool/RsaCtfTool#307]
Hi,
the hastads attack doesn't seem to work anymore:
`python RsaCtfTool.py --attack hastads --publickey "examples/hastads*" --uncipherfile "examples/cipher1,examples/cipher2,examples/cipher3"`

Error message fromRsaCtfTool/attacks/multi_keys/hastads.py:
"bytes must be in range(0, 256)"
This seems to create a byte from an 3-digit decimal-number extracted from "nth" (??) where the value sometimes exceeds 256:

```
 try:
    unciphered_ = b""
    #print(str(nth))
    for i in range(0, len(str(nth)), 3):
        _ = str(nth)[i : i + 3]
        print(_)
        unciphered_ += bytes([int(_)]) # This seems to raise the exception
    unciphered.append(unciphered_)
except Exception as ex:
```

**Comment by Ganapati** [comment]
Hi, thanks for this finding.
I have no time to patch it, can you make a pull request ?
