### ISSUE TITLE
Can't import default_backend

### ISSUE THREAD

**Issue by jedai47** [RsaCtfTool/RsaCtfTool#315]
Hi,
So I've got the following error on my mac, im using python3.9:

`python RsaCtfTool.py
Traceback (most recent call last):
  File "/Users/macpro/RsaCtfTool/RsaCtfTool.py", line 20, in <module>
    from lib.rsa_attack import RSAAttack
  File "/Users/macpro/RsaCtfTool/lib/rsa_attack.py", line 6, in <module>
    from lib.keys_wrapper import PublicKey, PrivateKey
  File "/Users/macpro/RsaCtfTool/lib/keys_wrapper.py", line 11, in <module>
    from cryptography.hazmat.backends import default_backend
ImportError: cannot import name 'default_backend' from 'cryptography.hazmat.backends' (unknown location)`

**Comment by Ganapati** [comment]
I think you have to install `python-dev` and `libffi-dev` on your os.
Try it and let me know :)

**Comment by daedalus** [comment]
this bug seems not to be related to RsaCtfTool but to de hazmat library.

**Comment by daedalus** [comment]
I'm closing this
