### ISSUE TITLE
Fix for RsaCtfTool

### ISSUE THREAD

**Issue by saffarfe** [RsaCtfTool/RsaCtfTool#326]
from lib import RSAAttack
ImportError: cannot import name 'RSAAttack' from 'lib' (/home/kali/Desktop/RsaCtfTool/lib/__init__.py)

just change the name in lib file jsut in case thats not a problem but i came a cross
but here is the problem i had 
ISSUE: 

eroor from:

 from lib import RSAAttack
TypeError: 'module' object is not callable

FROM::

    attackobj = RSAAttack(args)

just change the line 404 
TO :::

    attackobj = RSAAttack.RSAAttack(args)

**Comment by daedalus** [comment]
Hi,
The line `from lib import RSAAttack` doesnt exist in the current code, it seems you are using either an old version of the code or a modified version.
Please try with the latest version.
