### ISSUE TITLE
can't find lib.number_theory

### ISSUE THREAD

**Issue by Zhangfredy** [RsaCtfTool/RsaCtfTool#355]
maybe you delete this file,please upload it.😂

**Comment by MighN9ne** [comment]
ModuleNotFoundError: No module named 'lib.number_theory'

**Comment by benwong01f611** [comment]
It seems that the module was planned to renamed to number_theory, but it is missing after commit 70b62ec. You can copy the contents from [here](https://raw.githubusercontent.com/RsaCtfTool/RsaCtfTool/e8c9b6915e9dee1fed58a2f25a002876d27b7284/lib/rsalibnum.py), put it in lib folder and name it number_theory.py and it should work.

**Comment by Zhangfredy** [comment]
> 

Thanks.I get it.
