### ISSUE TITLE
factordb-pycli library & Sieve of Atkin

### ISSUE THREAD

**Issue by francesco1119** [RsaCtfTool/RsaCtfTool#361]
First of all thank you so much for you developing such amazing tool. 

I checked your script and I realized that you are not using https://pypi.org/project/factordb-pycli/ for querying FactorDB. Don't you think it would be easier? 

Also, do you think it would be possible to add the Sieve of Atkin https://en.wikipedia.org/wiki/Sieve_of_Atkin ? 

Thank you

**Comment by daedalus** [comment]
At first it used it but some other dev changed it.
About sirve of Atkin, currently the project uses the prime generator and test of gmpy, gmpy2 wherever it's needed, sieves are not used beacuse they use too much ram than to do a probabilistic test like miller Rabin, bpsw, etc...gmpy uses them internaly

**Comment by francesco1119** [comment]
Thank you.
