### ISSUE TITLE
Setting permissions of DOT_SAGE directory so only you can read and write it.\n0\n'

### ISSUE THREAD

**Issue by francesco1119** [RsaCtfTool/RsaCtfTool#362]
I encountered the error: 

`invalid literal for int() with base 10: b Setting permissions of DOT_SAGE directory so only you can read and write it.\n0\n'
`
I fixed it by doing: 

```
chown -R bobby:bobby /home/bobby/.sage/  
chmod -R 777 /home/bobby/.sage/
```

You can close this ticket

**Comment by francesco1119** [comment]
FYI,

I installed Sage not with `sudo dnf install sagemath` but with `sudo apt-get install sagemath`

**Comment by daedalus** [comment]
Please delete ~.sage and try again without changing permissions

**Comment by francesco1119** [comment]
I did: 

1. apt-get purge sagemath
2. apt-get autoclean
3. rm -R /home/bobby/.sage
4. apt-get install sagemath

And now the error is back: 

```
[!] An exception has occurred during the attack. Please check your inputs.
[!] invalid literal for int() with base 10: b'Setting permissions of DOT_SAGE directory so only you can read and write it.\n0\n'
[!] Traceback (most recent call last):
  File "/mnt/c/Users/franc/OneDrive/Documents/GitHub/RsaCtfTool-master/lib/rsa_attack.py", line 311, in attack_single_key
    self.publickey, self.cipher
  File "/mnt/c/Users/franc/OneDrive/Documents/GitHub/RsaCtfTool-master/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/mnt/c/Users/franc/OneDrive/Documents/GitHub/RsaCtfTool-master/attacks/single_key/boneh_durfee.py", line 32, in attack
    stderr=subprocess.DEVNULL,
ValueError: invalid literal for int() with base 10: b'Setting permissions of DOT_SAGE directory so only you can read and write it.\n0\n'
```
![image](https://user-images.githubusercontent.com/3397477/188914965-fd19f7f1-aa36-4c2b-94fe-eb3f5aed31d0.png)

**Comment by daedalus** [comment]
What happens if you just run sagemath?

**Comment by francesco1119** [comment]
Let me know what command I should use to run it

**Comment by daedalus** [comment]
just plain: 'sage'

**Comment by francesco1119** [comment]
It works perfectly: 

![image](https://user-images.githubusercontent.com/3397477/189212805-74640481-5a70-40cb-891a-0cb2147c9b3d.png)

I'm using WLS2 on Windows 10 and these are the permissions: 

![image](https://user-images.githubusercontent.com/3397477/189213108-f0632766-5660-426a-8e9c-7877ce631a34.png)

As soon as I put `777 `everything works

**Comment by daedalus** [comment]
WSL is not am official supported platform for this project.
Please try it on a virtual machine.
