### ISSUE TITLE
 'PublicKey' object has no attribute 'd'.

### ISSUE THREAD

**Issue by gsons** [RsaCtfTool/RsaCtfTool#373]
## the public key is from example.but not work. here the error .
![image](https://user-images.githubusercontent.com/15610655/192480675-8bc3ccb7-b6a5-49d4-ae79-6da7dd505807.png)

**Comment by daedalus** [comment]
The attack is only for partial private keys not public keys

**Comment by daedalus** [comment]
Please try:

`python3 RsaCtfTool.py --attack partial_q --key  examples/masked.pem`

To see how the attack works

Added a catch for the case where there is only a publickey provided [28acb89](https://github.com/RsaCtfTool/RsaCtfTool/commit/28acb893d41d0b5105bdc35fbeac77112ae8f191)
