### ISSUE TITLE
NameError: name 'mul' is not defined

### ISSUE THREAD

**Issue by PeterisP** [RsaCtfTool/RsaCtfTool#374]
Following the installation instructions listed in readme results in the following error after "[*] Performing common_factors attack."

```
File "[redacted]/RsaCtfTool/lib/number_theory.py", line 380, in ProductTree
    s = list(map(mul, s[0 : l >> 1], s[l >> 1 :]))
NameError: name 'mul' is not defined
```

This was the case both on MacOS and Kali Linux.

**Comment by daedalus** [comment]
Should be solved
