### ISSUE TITLE
My previously released album is now on the blockchain 😎

### ISSUE THREAD

**Issue by Trapbuckz** [RsaCtfTool/RsaCtfTool#378]
<blockquote class="twitter-tweet"><p lang="und" dir="ltr">Мой ранее изданный альбом теперь на блокчейне <br><br>My previously released album is now on the blockchain 😎<a href="https://t.co/LVz2mWT3Uc">https://t.co/LVz2mWT3Uc</a> <a href="https://t.co/I5xZWrVlZm">pic.twitter.com/I5xZWrVlZm</a></p>&mdash; trapbuckz.eth (@trapbuckz) <a href="https://twitter.com/trapbuckz/status/1586784599715110913?ref_src=twsrc%5Etfw">October 30, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by daedalus** [comment]
spam!
