### ISSUE TITLE
About XYXZ / NSIF Rename attack 

### ISSUE THREAD

**Issue by pedroelbanquero** [RsaCtfTool/RsaCtfTool#380]
just tbe sure final function is this , because when i did in the past i put a C file and was different from that . take a look, i add another post about how to improve .

this function factorize with P - Q  in a modular way .

![image](https://user-images.githubusercontent.com/60758685/200158901-9639b1ce-26d6-4598-b389-be86921d19d4.png)

![image](https://user-images.githubusercontent.com/60758685/200158929-4dcd2993-5dea-44aa-90c4-075a2a2459a9.png)

```
ex = 1826379812379156297616109238798712634987623891298419

{- | For result 0 is the period , if period is NSI is common factor of N.  -}
tryperiod n period _ = (powMod 2 (ex * (modular_inverse ex period) - 1) n) - 1


{- | N is the pubkey, tries is the number of tries in the loop, until when try to sum 1, distance is the starting distance  -}
nsif n tries distance
	| d /=1 && d /= n = (div n d,d,divcar)
	| otherwise = (0,0,0)
	where
	out2 = reverse ((1,1): take 1 (dropWhile (\(r,u)-> r==1 && r /= n ) $ map (\x-> (gcd (n) ((tryperiod ((n)) ((n)^2-x^2) x)  ),x)) $ [distance..distance+tries]))
	d = fst $ head out2
	divcar = snd $ head out2

```

**Comment by daedalus** [comment]
Sorry but what the acronym nsif stands for?

**Comment by daedalus** [comment]
Please I you want your PRs to be merged try to send them in python (This project is mostly written in python and sage)
We can't support every wild programing language that is out there.

**Comment by pedroelbanquero** [comment]
Well, seem you change NSIF by XYXZ, just to check to be sure is the same algo, i will update the next in python directly , i'm preparing some algos more, thank you
