### ISSUE TITLE
UnboundLocalError: local variable 'S' referenced before assignment in lib/number_theory.py", line 412, in chinese_remainder

### ISSUE THREAD

**Issue by shinmai** [RsaCtfTool/RsaCtfTool#385]
Seems the commit 24eb38a7d6c0837bf40ec3d4ca79e7cf94c09f25 inadvertently erased initialisation for the variable `S` causing the above error e.g. using `hastads`.

**Comment by daedalus** [comment]
fixed in [e823541](https://github.com/RsaCtfTool/RsaCtfTool/commit/e823541402e8040e01f51063f0814736a55e452d)
