### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by daedalus** [RsaCtfTool/RsaCtfTool#391]
I would like to address this issue in an open manner.

Hi @Ganapati would you like to re license the project to a more standar license.

I think it will be a gain.

**Comment by Ganapati** [comment]
hi! i haven't been here in a while.
If you find a more suitable license, I'll be pleased to change it.

**Comment by daedalus** [comment]
@Ganapai I'm for GPLv3 personally, but I dont know if it is the best...

**Comment by daedalus** [comment]
Hi @Ganapati what FLOSS license would you like to use for now on?
