### ISSUE TITLE
Add min, max and default timeout to helptext

### ISSUE THREAD

**Issue by jensMF** [RsaCtfTool/RsaCtfTool#395]
Hi,

nice tool :-)

I think it would be good to give the information what the min and max values for --timeout is. The default value and maybe a unit like s or ms would be nice to know, too.

Some attacks are throwing exceptions when the time runs out others don't. Maybe this could be unified.

Thanks for the tool!

**Comment by daedalus** [comment]
Hi, 
Timeout is a fixed value, seteable by command line.
You may want to know min/max/avg of the total elapsed time for each attack and maybe globaly for the whole.
I'm currently out of time to implement that but if you like to send a PR I'll be glad to merge.

**Comment by daedalus** [comment]
I think is implemented now, i'm closing this.

**Comment by jensMF** [comment]
Thank you for your work. The timing information you added are really interesting.
Sorry I could not make clear what I meant. I try to make it more clear.
When I type `python RsaCtfTool.py -h` there is this line `--timeout TIMEOUT     Timeout for long attacks.` in the helptext.
What I think would be useful is to know:
    - What is the default value for `TIMEOUT`? (so one can raise or lower it)
    - What is the minimum Value for `TIMEOUT`?
    - What is the maximum Value for `TIMEOUT`?
    - [optional] What is the unit for `TIMEOUT`? (µs, ms, or s or maybe something different)?

Thanks in advance for looking into this and for the tool itself. I really like it.

**Comment by daedalus** [comment]
Timeout is 60 seconds and the unit is seconds, it's a global setting, there is no min/max, just one global value for every attack, when it's surpassed, the attack gets signaled (see timeout.py).
The time out will be global to keep simplicity.
If you want to know more I invite you to read the code.
