### ISSUE TITLE
FactorDB attacks issue 

### ISSUE THREAD

**Issue by Zeecka** [RsaCtfTool/RsaCtfTool#400]
Attacks relying on FactorDB doesn't work anymore. This may be related: https://github.com/ryosan-470/factordb-python/issues/11.
```bash
./test.sh
```
![image](https://user-images.githubusercontent.com/24873615/216845017-d9685265-8328-4f5c-9f87-532600bc5ea5.png)

**Comment by daedalus** [comment]
We need to wait for that to be fixed upstream, unfortunately nothing that we can do.

**Comment by Zeecka** [comment]
Update: After some checks, the Issue is not related to https://github.com/ryosan-470/factordb-python/issues/11. FactorDB is not even called with `./RsaCtfTool.py --publickey "examples/factordb_parse.pub" --private --attack factordb` and `./RsaCtfTool.py --publickey "examples/factordb_parse.pub" --private --tests --attack factordb` (python 3.10). Also, the mentionned issue only affect huge numbers (no regression).
