### ISSUE TITLE
Odd clang error | clang: error: invalid arch name '-arch aarch64'

### ISSUE THREAD

**Issue by A-z-z-y** [RsaCtfTool/RsaCtfTool#408]
[log.txt](https://github.com/RsaCtfTool/RsaCtfTool/files/10828409/log.txt)

I've tried installing multiple times but I keep getting the same error. Installing it on it's own with `pip3 install pycryptodome` which seems to work, but then retrying installing the requirements gets me the same error again.

**Comment by daedalus** [comment]
It seems to be a bug upstream, sorry but we can do nothing about it, try asking for help in the pycryptodome project, cleaning you pip cache, etc...
