### ISSUE TITLE
private key printing: TypeError: __str__ returned non-string (type NoneType)

### ISSUE THREAD

**Issue by agent-0007** [RsaCtfTool/RsaCtfTool#415]
`RsaCtfTool$ ./RsaCtfTool.py --private --publickey public.pem

[*] Testing key public.pem.
attack initialized...
attack initialized...
[*] Performing fibonacci_gcd attack on public.pem.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9999/9999 [00:00<00:00, 84380.26it/s]
[+] Time elapsed: 0.1214 sec.
[*] Performing nonRSA attack on public.pem.
[*] Attack success with nonRSA method !
[+] Total time elapsed min,max,avg: 0.1214/0.1214/0.1214 sec.

Results for public.pem:

Private key :
Traceback (most recent call last):
  File "/home/max/trash/public/RSA/RsaCtfTool/./RsaCtfTool.py", line 524, in <module>
    main()
  File "/home/max/trash/public/RSA/RsaCtfTool/./RsaCtfTool.py", line 517, in main
    args = run_attacks(args, logger)
  File "/home/max/trash/public/RSA/RsaCtfTool/./RsaCtfTool.py", line 246, in run_attacks
    attackobj.attack_single_key(publickey, selected_attacks)
  File "/home/max/trash/public/RSA/RsaCtfTool/lib/rsa_attack.py", line 368, in attack_single_key
    self.print_results_details(publickey)
  File "/home/max/trash/public/RSA/RsaCtfTool/lib/rsa_attack.py", line 100, in print_results_details
    print_results(self.args, publickeyname, self.priv_key, self.unciphered)
  File "/home/max/trash/public/RSA/RsaCtfTool/lib/utils.py", line 104, in print_results
    if str(priv_key) != "":
TypeError: __str__ returned non-string (type NoneType)
`

**Comment by daedalus** [comment]
Please share your publickey for reproducibility

**Comment by agent-0007** [comment]
Hello, this is my public key. This key generated for CTF event, can be interesting.

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEBITsFfW/evEUntbdCGsHp
PM/+p2xPCHSZHPP6zw6rnvZGohg5ggtNZTqRa2jyWOnT98K6BU5K8F8+TWGz3nct
KtIziw6ubqCPIHbk5LCKsgkg+miF5sRN7BvuKKh2U8dLy56fEpTeiki9YUZSo9ZZ
3857iURhDyW/r5NumlQWfE0ifRbTLmXqRYtp1g3s1/oDTBs72GJxcWTneF6wbcxb
iLqiYuQxIOVGZcDLyz6tUbCgCBm06R1IctP753JOA6txvK+LuEx03slqrfyxhlOo
8FOT1mYGmSO8e5sxNj1tbZtFn0bbW6+W+EBKrxqDHw24qtfZOkJW6BVrK3B1egEg
kwIDAQAB
-----END PUBLIC KEY-----

**Comment by romulusFR** [comment]
It looks like it's due to `PrivateKey.__str__` returning None as  `self.key` is still `None` (only n, e and d are known, not p and q i'll say)

```python
    def __str__(self):
        # print(type(self.key))
        """Print armored private key"""
        if self.key is not None:
            return self.key.exportKey().decode("utf-8")
```

**Comment by daedalus** [comment]
Hi, I was looking at your provided modulus and it's prime...

**Comment by daedalus** [comment]
Solved
