### ISSUE TITLE
why python3.7 wsl cannot run?

### ISSUE THREAD

**Issue by qahehe** [RsaCtfTool/RsaCtfTool#416]
![image](https://user-images.githubusercontent.com/25258443/235475544-c929146d-4ef5-42fc-bd8d-4568e0f5edf1.png)
look at the above , i use miniconda to create  python3.7 environment and install successfully the requirement. How can i solve this problem ? upgrade the python environment?
my configuration is wins 10  and wsl ubuntu 20.04LTS

**Comment by daedalus** [comment]
It's an upstream problem with functools for wsl, nothing to do here.

**Comment by qahehe** [comment]
> It's an upstream problem with functools for wsl, nothing to do here.

thanks,bro

**Comment by qahehe** [comment]
> It's an upstream problem with functools for wsl, nothing to do here.

i think it's a problem with python version, i  right now create a python3.9 virtual environment and i install the requirement successfully ,maybe functools need python3.9 or higher version.

**Comment by romulusFR** [comment]
According to the doc, `cache` has been added in version 3.9 indeed <https://docs.python.org/3/library/functools.html#functools.cache>

**Comment by daedalus** [comment]
Thanks, added to the readme.
