### ISSUE TITLE
couldn't attack

### ISSUE THREAD

**Issue by d4ydramer** [RsaCtfTool/RsaCtfTool#417]
![image](https://user-images.githubusercontent.com/65070121/236612067-b3d82542-f6fc-4d01-be2f-aeea70f79a8f.png)

**Comment by daedalus** [comment]
Please can you share your public key pem and chipher.bin to reproduce the issue?

**Comment by Luk164** [comment]
Same problem here. I figured out it happens in the `uncipher_file` method.

```
def uncipher_file(args, logger):
    uncipher_array = []
    for uncipher in args.uncipherfile.split(","):
        try:
            with open(uncipher, "rb") as cipherfile_fd:
                uncipher = get_base64_value(cipherfile_fd.read())
                uncipher_array.append(uncipher)
        except OSError:
            logger.info("--uncipherfile : file not found or not readable.")
            return False
    args.uncipher = uncipher_array
    # If we have a private key in input and uncipher in args (or uncipherfile)
    if args.key and args.uncipher: # <---- the function expects key even though no attacks were run yet. Key is thus empty and the method returns false, ending the execution
        priv_key = PrivateKey(filename=args.key, password=args.password)
        unciphers = priv_key.decrypt(args.uncipher)
        print_results(args, None, priv_key, unciphers)
        return True
```

I am attaching my files along with an example of the command used:
`RsaCtfTool.py --publickey key.pub --uncipherfile flag.enc --private`
[Weak RSA.zip](https://github.com/RsaCtfTool/RsaCtfTool/files/11487537/Weak.RSA.zip)

**Comment by noahcampbell** [comment]
Where uncipher_file is called around line ~430...there is an:

```
  else: 
     sys.exit(-1)
```

remove that and you're going to be able to perform your attack.

**Comment by noahcampbell** [comment]
Looks like a refactor from this [commit](https://github.com/RsaCtfTool/RsaCtfTool/commit/4da781f65e359781d691302ec2061e79a2ab0bf6) slightly altered the functionality.

**Comment by Arnulfo-campos** [comment]
when performing an attack it says it is successful but does not show the output values.
![image](https://github.com/RsaCtfTool/RsaCtfTool/assets/114844388/adea650b-7fc7-4b07-a1af-c5e91f217c15)
