### ISSUE TITLE
rsactftool uncipher file with the wrong output

### ISSUE THREAD

**Issue by xiaochunrilihe** [RsaCtfTool/RsaCtfTool#422]
original challenge
[JarvisOJ: Medium RSA](https://www.ruanx.net/rsa-solutions/)
RsaCtfTool Result: 
![image](https://github.com/RsaCtfTool/RsaCtfTool/assets/31942426/e0766c05-3545-42f8-aebb-a8715d767d10)
Openssl Result:
![image](https://github.com/RsaCtfTool/RsaCtfTool/assets/31942426/385cb8c1-5a2f-48bc-85c9-22fa44545d22)
Did I do sth wrong ?

**Comment by daedalus** [comment]
For reproducibility please post here your public.pem and flag.enc files.

**Comment by xiaochunrilihe** [comment]
[public.pem and flag.enc files](https://dn.jarvisoj.com/challengefiles/mediumRSA.rar.07aab25c9c54464a8c9821ca28503330)
[mediumRSA.zip](https://github.com/RsaCtfTool/RsaCtfTool/files/11827287/mediumRSA.zip)

**Comment by daedalus** [comment]
Try git pull and run again, it sould be working.

**Comment by daedalus** [comment]
I'm closing this
