### ISSUE TITLE
PyPI project name `rsactftool` is occupied by an unknown fork

### ISSUE THREAD

**Issue by ttimasdf** [RsaCtfTool/RsaCtfTool#429]
The PyPI project with the same name (https://pypi.org/project/rsactftool/) was uploaded from a fork of this project (https://github.com/borari/RsaCtfTool) maintained by @borari.
Upon examining the changes, it appears that the maintainer mainly altered the directory structures and development stuffs like poetry configurations. It seems that he made these modifications for a good reason - providing simpler installation through PyPI and created a functional entrypoint script for Windows (which is also something I am planning to do!). But it appears that this fork has been inactive for quite some time now.

Is there any chance that these changes could get merged or implemented in a similar way so that users can simply do
```bash
pip install git+https://github.com/RsaCtfTool/RsaCtfTool.git
# or better
pip install rsactftool
```
for installation and run
```bash
rsactftool --help
```
from anywhere?

**Comment by daedalus** [comment]
If you would like to send a PR implementing the functonality will be greatly appreciated.

**Comment by borari** [comment]
I'm not sure if the changes I made are considered "best practice" or in line with the code style/design of this project. I can submit a pull request from the fork that's something you want @ttimasdf.
