### ISSUE TITLE
decryptfile failed

### ISSUE THREAD

**Issue by zhangyouyi125** [RsaCtfTool/RsaCtfTool#478]
publickety decrypt file failed ,` Private key and decrypted data are required.`

```
(base) ➜  RsaCtfTool git:(master) ✗ python RsaCtfTool.py --publickey key.pem --decryptfile cipher.bin
private argument is not set, the private key will not be displayed, even if recovered.
Private key and decrypted data are required.
```

**Comment by daedalus** [comment]
Please try this and paste the results:

`./RsaCtfTool.py --publickey examples/primefac.pub --decryptfile examples/cipher1,examples/cipher2,examples/cipher3`

**Comment by zhangyouyi125** [comment]
> Please try this and paste the results:
> 
> `./RsaCtfTool.py --publickey examples/primefac.pub --decryptfile examples/cipher1,examples/cipher2,examples/cipher3`

I reloaded the project, and it worked. Thanks!
