### ISSUE TITLE
Where are the decrypted results stored

### ISSUE THREAD

**Issue by PAnkELi** [RsaCtfTool/RsaCtfTool#481]
`Python RsaCtfTool.py -n xxx -e xxx --password xxx`
After the above code is executed, only the decrypting success prompt is output, and no private key or plaintext is output:

[*] Attack success with wiener method !
[+] Total time elapsed min,max,avg: 0.0003/60.0222/16.6459 sec.

**Comment by daedalus** [comment]
Please refer to the readme under the Print private key section.
