### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by Zandroid505** [RsaCtfTool/RsaCtfTool#483]
Hi, I'm very interested in this project and would love to contribute. Before contributing, I would like to run the docker image and run the examples to better understand it.

I am unfortunately unable to pull the pre-built docker image from the registry either because it doesn't exist or I don't have access. This is the error it gives me: 

`Error response from daemon: pull access denied for rsactftool/rsactftool, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

I then attempted to build the image from the docker file, but got the following error:

``ERROR [2/7] RUN apk update &&     apk add --no-cache     gmp-dev mpfr-dev mpc1-dev python3 python3-dev py3-pip gcc musl-dev openssl-dev libffi-dev py3-wheel git gcc g++ make cmake git sagemath                                                    2.1s
 > [2/7] RUN apk update &&     apk add --no-cache     gmp-dev mpfr-dev mpc1-dev python3 python3-dev py3-pip gcc musl-dev openssl-dev libffi-dev py3-wheel git gcc g++ make cmake git sagemath:                                                               
0.382 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz                                                                                                                                                                          
0.916 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz                                                                                                                                                                     
1.387 v3.19.2-72-g530edf7d7d4 [https://dl-cdn.alpinelinux.org/alpine/v3.19/main]                                                                                                                                                                             
1.387 v3.19.2-76-gd4cf04b90a9 [https://dl-cdn.alpinelinux.org/alpine/v3.19/community]                                                                                                                                                                        
1.387 OK: 23032 distinct packages available
1.459 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
1.762 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
2.029 ERROR: unable to select packages:
2.029   sagemath (no such package):
2.029     required by: world[sagemath]
Dockerfile:2
   1 |     FROM alpine:3.19
   2 | >>> RUN apk update && \
   3 | >>>     apk add --no-cache \
   4 | >>>     gmp-dev mpfr-dev mpc1-dev python3 python3-dev py3-pip gcc musl-dev openssl-dev libffi-dev py3-wheel git gcc g++ make cmake git sagemath
   5 |     WORKDIR /opt
ERROR: failed to solve: process "/bin/sh -c apk update &&     apk add --no-cache     gmp-dev mpfr-dev mpc1-dev python3 python3-dev py3-pip gcc musl-dev openssl-dev libffi-dev py3-wheel git gcc g++ make cmake git sagemath" did not complete successfully: exit code: 1``

I looked into it a while ago so definitely take this with a grain of salt, but I believe it fails because sagemath isn't supported on Alpine Linux.

My question is am I the only one having these issues? If not, could I try to modify the docker file in a pull request to attempt to fix it?

Thank you and please let me know if you need any additional information.

**Comment by daedalus** [comment]
Hi, first of all thank you for your interest.
Secondly, we haven't published a container into the docker hub, that's why it doesn't fetch anything. So in order to be able to run the application in docker you need to build the docker file by yourself.
Please tell me if this helps.

**Comment by Zandroid505** [comment]
Thank you for your response.

I see. Do you think I can change the README (in a pull request) to exclude the step to pull the image since it isn't published on docker hub?

Also, I did try to build both docker files and unfortunately, both fail. The minimal installation (*Dockerfile*) fails with the error shown in my previous message. I just attempted to build the full docker file (*Dockerfile_full*) and it also failed. It failed when trying to install the python packages specified in *optional-requirements.txt*.

Do you also have these issues when building the image? If not, the issue might be on my end.

**Comment by daedalus** [comment]
> I see. Do you think I can change the README (in a pull request) to exclude the step to pull the image since it isn't published on docker hub?

Yes please

**Comment by Zandroid505** [comment]
Great! I'll try to do a pull request before the end of this week :).

Also, are you able to build the docker image on your computer? Both of the docker files fail to build for me unfortunately and I am unsure if it is just something with my local environment or if there is something wrong with the docker files themselves. I detailed the errors I was getting in my previous messages.

I am attempting to build them with the following commands:
- Minimal Version (*Dockerfile*): `docker build -t rsactftool/rsactftool .`
- Full Version (*Dockerfile_full*): `docker build -t rsactftool/rsactftool . -f ./Dockerfile_full`

Am I missing any required flags or arguments needed to build the image?

**Comment by Zandroid505** [comment]
Hi, I just created the pull request to update the docker section of the README :)

**Comment by Zandroid505** [comment]
Closing this because another contributor fixed the docker file and I am now able to build the image and run the container.
